image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --build-arg version=$(cat VERSION) -t $CI_REGISTRY_IMAGE:$(cat VERSION) -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$(cat VERSION) 
    - docker push $CI_REGISTRY_IMAGE:latest 

