image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - build

variables:
  CONTAINER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE_TAG -t $CONTAINER_IMAGE_LATEST .
    - docker push $CONTAINER_IMAGE_TAG
    - docker push $CONTAINER_IMAGE_LATEST

